### ISSUE TITLE
NPE on player login

### ISSUE THREAD

**Issue by TheKinrar** [TheKinrar/Papyrus#15]
```
java.lang.NullPointerException: null
        at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:303) ~[papyrus.jar:git-Papyrus-33]
        at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:179) ~[papyrus.jar:git-Papyrus-33]
        at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:70) ~[papyrus.jar:git-Papyrus-33]
        at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256) ~[papyrus.jar:git-Papyrus-33]
        at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139) ~[papyrus.jar:git-Papyrus-33]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1261) ~[papyrus.jar:git-Papyrus-33]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:431) ~[papyrus.jar:git-Papyrus-33]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[papyrus.jar:git-Papyrus-33]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[papyrus.jar:git-Papyrus-33]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Comment by TheKinrar** [comment]
Happens on servers without hybrid mode because hybrid profile is null

**Comment by TheKinrar** [comment]
New NPE after login
```
20:57:16 ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
        at fr.thekinrar.papyrus.hybrid.CraftHybridEngine.tick(CraftHybridEngine.java:78) ~[papyrus.jar:git-Papyrus-34]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1182) ~[papyrus.jar:git-Papyrus-34]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:431) ~[papyrus.jar:git-Papyrus-34]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[papyrus.jar:git-Papyrus-34]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[papyrus.jar:git-Papyrus-34]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```
